spring:
  profiles:
    active:
      -dev

---

server:
  port: 8002
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-provider-stu
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_for_cloud
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
  instance:
    instance-id: microservicecloud-provider-stu-8001
    prefer-ip-address: true #访问路径显示ip

mybatis:
  mapper-locations:
  - classpath:mapper/**/*.xml
  configuration:
    cache-enabled: true

---
server:
  port: 8011
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-provider-stu
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_for_cloud
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7011:7011/eureka/
  instance:
    instance-id: microservicecloud-provider-stu-8001
    prefer-ip-address: true #访问路径显示ip

mybatis:
  mapper-locations:
  - classpath:mapper/**/*.xml
  configuration:
    cache-enabled: true